# Generated by Django 5.2.7 on 2025-10-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('quantidade_pessoas', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Em espera', 'Em espera'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada')], default='Em espera', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
