# Generated by Django 5.2.7 on 2025-10-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora',
            field=models.TimeField(default='12:00:00'),
        ),
    ]
